[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.8.0"

[[bench]]
name = "secret_entrance_bench"
harness = false

[[bench]]
name = "gift_shop"
harness = false
